name: "Code Validation"

permissions: write-all

on:
  push:
    branches-ignore:
      - main

jobs:  
  job_terraform:
    name: "Terraform plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.GITHUBOIDC_AWSROLE }}
          role-session-name: github-oidc

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_AWS_ROOT_LAB }}

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
  
  job_tflint:
    name: "TFLint"
    runs-on: ubuntu-latest
    needs: job_terraform
    
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
        
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
      
      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

  job_checkov:
    name: "Checkov analyses"
    runs-on: ubuntu-latest
    needs: job_tflint
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
